// swift-tools-version: 5.9
// Auto-generated by GitHub Actions release workflow – do not edit manually.
import PackageDescription

let package = Package(
    name: "DadoMatchShared",
    platforms: [
        .iOS(.v16)
    ],
    products: [
        .library(
            name: "DadoMatchShared",
            targets: ["DadoMatchSharedWrapper"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/RevenueCat/purchases-hybrid-common.git", exact: "17.32.0"),
    ],
    targets: [
        .binaryTarget(
            name: "DadoMatchSharedBinary",
            url: "https://github.com/felipechaux/dado-match-shared/releases/download/v1.0.1/DadoMatchShared.xcframework.zip",
            checksum: "45a076ca15ed4c6e39128e678aa610858acfe1291e4086f775f0f99ae6af23f8"
        ),
        .target(
            name: "DadoMatchSharedWrapper",
            dependencies: [
                "DadoMatchSharedBinary",
                .product(name: "PurchasesHybridCommon", package: "purchases-hybrid-common"),
                .product(name: "PurchasesHybridCommonUI", package: "purchases-hybrid-common"),
            ]
        )
    ]
)
