package com.dadomatch.shared.core.data

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.dadomatch.shared.feature.success.data.local.dao.SuccessDao
import com.dadomatch.shared.feature.success.data.local.entity.SuccessEntity

@Database(
    entities = [SuccessEntity::class],
    version = 1,
    exportSchema = false
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun successDao(): SuccessDao
}

// The actual implementations with initialize() are generated by KSP
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
